### ISSUE TITLE
Скласти таймлайн

### ISSUE THREAD

**Issue by ValentynChepiha** [ValentynChepiha/homepage#6]
Скласти список всіх (важливих) життєвих подій, визначних дат, досягнень, періодів, що дали приємний і неприємний досвід, тощо. В цьому конкретному випадку довгих списків не буває, натомість бувають погано згорнуті, тому пакуємо сюди все підряд, а про "лишні" події можна буде промовчати пізніше. Список повинен бути систематизованим і посортованим в такий спосіб, щоб читач швидко зрозумів "паттерн" і міг легко орієнтуватись в просторі і часі цього резюме.

**Comment by MrMizerakl** [comment]
1) Developer of the PrJSC «Elita»
Sosnytsia, Chernihiv reg.,
Since April 2017 till June 2019

Написання та підтримка програмних засобів та інтернет ресурсів компанії.

Visual C++, PostgreSQL, VFP7, VBA, 1С 

2) Head of the Sosnytsia ІТ Department, Affiliate of Mena State Tax Office of Ukraine 
Sosnytsia, Chernihiv reg.,
July 2004 till June 2013. 
Since June 2013 till April 2016 - Chief state inspector

- practical implementation of information systems on the basis of DBMS: Oracle, FireBird, InterBase, FoxPro. Generation of analytical information in taxation. Developing programs for retrieving data from DB. Writing system of WEB-pages using HTML, PHP, JS, JQuery, PL/SQL Oracle, SQL others DB. Ensured the exchange of information between different databases. My program is still in use by the users;
- Oracle, FireBird, InterBase, FoxPro administration (installing, optimization, database back-up, restoring DB, updating). Configured backup system that works until today;
- human resources management, work with legal entities and private entrepreneurs with the chief accountants and management;

PHP, JS, HTML, Oracle, Firebird, FVP7

3) Teacher of Physics and Informatics at Kostobobriv Secondary School of I-III grades
Kostobobriv vill., Semenivka distr., Chernihiv reg., 
August 2001 till June 2004.
teaching Physics and Informatics

Pascal, Delphi

II) Education: 
1) Chernihiv State Pedagogic University
Specialist.Mathematics and foundation for computer science.
1996-2001
Pascal, Delphi, Paradox

2) Chernihiv State Institute of Economics and 
Specialist.Accounting and Auditing.
2008-2010

3) 1986 - 1996 study in school
